### ISSUE TITLE
Big notes don't get added

### ISSUE THREAD

**Issue by FaronFaron** [1stupidgeek/save-deez-notes#2]
Big notes don't get added

**Comment by 1stupidgeek** [comment]
> Big notes don't get added

hmm, its because of the character limit of a message in discord, need to switch to files ASAP

**Comment by rurixd** [comment]
**Fixed**: https://github.com/1stupidgeek/save-deez-notes/pull/6/commits/0046a3f046a210db1bac934272f98b1434b0684f
